### ISSUE TITLE
Is this the official implementation?

### ISSUE THREAD

**Issue by faizankshaikh** [SashaZd/Jill#1]
Is this repo the official [jill](http://www.news.gatech.edu/2016/05/09/artificial-intelligence-course-creates-ai-teaching-assistant) implementation?

**Comment by faizankshaikh** [comment]
Is this repo the official [jill](http://www.news.gatech.edu/2016/05/09/artificial-intelligence-course-creates-ai-teaching-assistant) implementation

**Comment by SashaZd** [comment]
No. This is another project made before the AI TA that was also codenamed Jill.
